{% set version = "1.4-0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-metadat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/metadat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/metadat/metadat_{{ version }}.tar.gz
  sha256: 2a5d6dee053cc329bc5c03fb6058ed99312f8f56c15028fabcbfa21170ef3f05

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mathjaxr
  run:
    - r-base
    - r-mathjaxr

test:
  commands:
    - $R -e "library('metadat')"           # [not win]
    - "\"%R%\" -e \"library('metadat')\""  # [win]

about:
  home: https://github.com/wviechtb/metadat
  license: GPL-2.0-or-later
  summary: A collection of meta-analysis datasets for teaching purposes, illustrating/testing meta-analytic methods, and validating published analyses.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
