{% set version = "1.6-0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-metadat
  version: "{{ version|replace("-", "_") }}"

source:
  url:
    - {{ cran_mirror }}/src/contrib/metadat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/metadat/metadat_{{ version }}.tar.gz
  sha256: f5f2bb245d2241ed876e17b038c856732684f1884993546721b097b554c6e305

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mathjaxr
  run:
    - r-base
    - r-mathjaxr

test:
  commands:
    - $R -e "library('metadat')"           # [not win]
    - "\"%R%\" -e \"library('metadat')\""  # [win]

about:
  home: https://wviechtb.github.io/metadat/
  dev_url: https://github.com/wviechtb/metadat
  license: GPL-2.0-or-later
  summary: A collection of meta-analysis datasets for teaching purposes, illustrating/testing meta-analytic methods, and validating published analyses.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
